### PR TITLE
alphabetized definitions within glossary sections

### PR DESCRIPTION
**Pull request by joshuareagan**

### CODE REVIEW

**Comment by Fang-** [comment]
Not entirely sure how to feel about alphabetizing that tiny list of Nock terms at the start. The order there feels like the canonical one to me, makes a lot of sense, and the list is short enough to search without scrolling all over the place.  
Maybe that's just me though. I suppose there's something to be said for consistency with the rest of the page.

Also, some of the headers are `###### headers`, others are `<h6 id="word">headers</h6>`, and some are both. Not sure how Urbit's markdown rendering deals with this, but GitHub makes two `<h6>` elements for those that are both. It'd be nicest to have them all be  `<h6 id="word">`, so that they all can be #linked to.

**Comment by joshuareagan** [comment]
issue #202

**Comment by keatondunsford** [comment]
@joshuareagan @belisarius222 I'm thinking that the order of the Glossary as a whole should match the new proposed Hoon tutorial outline: i.e. it should go from Nock up. Even if those docs aren't written, I think the outline is good enough to start rearranging this section and potentially start adding more concepts.

What do you think about this?

**Comment by joshuareagan** [comment]
I left a comment on the issue thread about the glossary: #202

**Pull request merged**
