### PR TITLE
Write 3b

### PR DESCRIPTION
**Pull request by rmariani**
Wrote documentation for the previously undocumented 3b

### CODE REVIEW

**Comment by joshuareagan** [comment]
There's a lot of good work here!  That said, I'm not crazy about some of these headers, e.g., `++^rou:fl`.  This is pretty far removed from what we see in the code, and by itself it doesn't make much sense either.  I'd rather just have us cite the arm name, e.g., `++  rou`.  Context makes clear which door this arm is under.

**Comment by cgyarvin** [comment]
It’s a good stab but new Hoon will be much better at these kinds of names/paths.

**Comment by rmariani** [comment]
I suppose so. I just wanted to minimize confusion from stuff like a reader
ctrl+f-ing and finding different results

—
~lodleb-ritrul
https://urbit.org

**Comment by rmariani** [comment]
Alrighty, this new version lacks the offending `^`s

**Comment by rmariani** [comment]
This has a merge conflict and isn't in udon

**Pull request closed without merging**
