### PR TITLE
Added 'Fedora 29 (fresh linode)' build section.

### PR DESCRIPTION
**Pull request by jfranklin9000**
I just did this on a fresh Fedora 29 linode instance and these instructions worked for me.
They're less involved than the Fedora instructions already there.

### CODE REVIEW

**Comment by rmariani** [comment]
Can these instructions replace the "Fedora" instructions? I am not sure why we would need to specify that it's for "fresh linode."

**Comment by jfranklin9000** [comment]
I'm not sure.  This is the first time I built on Fedora.  Presumably somebody needed the other instructions to build.  Maybe on Fedora 28?  If I can setup a Fedora 28 instance I'll see if I can build with the newer instructions.  If not and we need both instructions I'll label them 'Fedora 28 and earlier' and 'Fedora 29'.

**Comment by ohAitch** [comment]
(This is somewhat off-topic, but how did we end up requiring both python2
and python3?)

**Comment by jfranklin9000** [comment]
### Testing methodology

As non-root user on host:

	sudo docker run -it fedora:29 /bin/bash

As `root` in `fedora:29` container:

	more /etc/fedora-release
	Fedora release 29 (Twenty Nine)

	dnf upgrade
	dnf install autoconf automake cmake ctags gcc gcc-c++ git meson gmp-devel libcurl-devel libsigsegv-devel libtool ncurses-devel ninja-build openssl openssl-devel pkgconfig python2 python3 ragel re2c wget

	useradd -m zod
	su zod

As `zod` in `fedora:29` container:

	cd ~
	git clone https://github.com/urbit/urbit
	cd urbit
	./scripts/bootstrap
	./scripts/build
	build/urbit
	Urbit: a personal server operating function
	https://urbit.org
	Version 0.7.3

I did those steps for the following:

	sudo docker run -it fedora:28 /bin/bash
	sudo docker run -it fedora:27 /bin/bash
	sudo docker run -it fedora:26 /bin/bash
	sudo docker run -it fedora:25 /bin/bash
	sudo docker run -it fedora:24 /bin/bash
	sudo docker run -it fedora:23 /bin/bash

They all worked except `fedora:23`
(`./scripts/build: line 5: ninja: command not found`).

I used the instructions in the 'Fedora 23 or earlier'
section and they worked for `fedora:23`.

I didn't test `fedora:22` or earlier.

**Comment by jfranklin9000** [comment]
### requiring both python2 and python3?

We don't seem to need `python2`.

As non-root user on host:

	sudo docker run -it fedora:29 /bin/bash

As `root` in `fedora:29` container:

	more /etc/fedora-release
	Fedora release 29 (Twenty Nine)

	dnf upgrade
	# no python2 or ragel (see below)
	dnf install autoconf automake cmake ctags gcc gcc-c++ git meson gmp-devel libcurl-devel libsigsegv-devel libtool ncurses-devel ninja-build openssl openssl-devel pkgconfig python3 re2c wget

	python --version
	bash: python: command not found
	python2 --version
	bash: python2: command not found
	python3 --version
	Python 3.7.2

	useradd -m zod
	su zod

As `zod` in `fedora:29` container:

	cd ~
	git clone https://github.com/urbit/urbit
	cd urbit
	./scripts/bootstrap
	./scripts/build
	build/urbit
	Urbit: a personal server operating function
	https://urbit.org
	Version 0.7.3

### ragel

`anachronism` used `ragel` to build `outside/anachronism/src/parser.c`.
(It turns out `outside/anachronism/src/parser.c` was committed in
`https://github.com/urbit/urbit/commit/35fc5494114eff9801584461559ac45ffe0c8875`
so we haven't used `ragel` since June 2015.)

`anachronism`  is no longer part of the project so `ragel` is no longer needed.

I'll delete `python2` and `ragel` in another PR if you want.

**Comment by rmariani** [comment]
Can you just delete them in this PR?

**Comment by jfranklin9000** [comment]
I'll do it later tonight.

**Comment by jfranklin9000** [comment]
I removed python2 and ragel from the build requirements.

**Comment by rmariani** [comment]
LGTM

**Pull request merged**
