### PR TITLE
adds initial glossary

### PR DESCRIPTION
**Pull request by joemfb**
I've covered Nock, I *think* I've covered Hoon. Arvo and general urbit-y concepts are yet to be defined.

I've added *TODO* wherever I was stuck, guessing, or more-than-usually confused.

I took a stab at some formatting, but there's lots of different ways this could be structured. Likewise, I moved things around until it felt like their order made sense, but I'm not at all sure that it's right ...

Finally, I'm not sure this is written in the right voice. It needs to strike the right balance tonally, since I image it'll be consulted quite a bit.

This glossary is provided AS IS, without warranty or encumbrance on it's author ;)

re #33, #26

### CODE REVIEW

**Comment by joemfb** [comment]
Also, the lines need to be wrapped to match the other docs.

**Comment by galenwp** [comment]
We usually use pandoc for this.

**Comment by joemfb** [comment]
You mean I could've written this in DocBook?

**Comment by joemfb** [comment]
@asgardiator took care of the TODOs, and @cgyarvin has made his edits. Best to stop the madness now before it spreads.

I'll open separate PRs for any additional definitions I want to add ... ;)

**Comment by joemfb** [comment]
Lotta commits here - if you'd like, I'd be happy to squash them down (and present a more *responsible* historical narrative)... 

/cc @juped

**Comment by juped** [comment]
Fortunately, I don't care about the docs repository that much. But if you feel like doing something, you could undo your misguided linearization? :)

**Comment by bshanks** [comment]
Here's a glossary/cheat sheet i made awhile ago:

http://www.bayleshanks.com/?action=browse&id=notes-computer-programming-hoon-hoonCheatSheet&raw=1

This is the same one i posted to the mailing list on 3/26/15. Feel free to copy any part of it. It's probably rather out of date and filled with errors. I would revise it and submit it as a pull request but i am not confident in the correctness or up-to-date-ness of my own understanding of Urbit.

**Comment by joemfb** [comment]
This is a great! I think a syntax reference would be really helpful, and I love the idea of an English->Hoon inverse lookup table.

**Comment by philipcmonk** [comment]
Is work continuing on this, or can it be merged?

**Comment by galenwp** [comment]
After a quick skim it looks pretty good.  I'd be inclined to put that up.

**Comment by cgyarvin** [comment]
I say, put it up.  It's conceptually flawed at a certain level, but what isn't?  :-)

**Comment by asgardiator** [comment]
A few inconsistencies on the stairway are definitely acceptable, if they help the passengers climb. Call this one the gateway doc.

**Comment by joemfb** [comment]
May that ringing endorsement serve as my epitaph!

"His work was conceptually flawed, but, really, what isn't?"

;)

More seriously, as I said on the urbit-dev thread, I'm happy to reshape
this if you'd rather it be a more cliche'd "glossary" ...

On Thursday, June 23, 2016, asgardiator <notifications@github.com> wrote:

> A few inconsistencies on the stairway are definitely acceptable, if they
> help the passengers climb. Call this one the gateway doc.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/docs/pull/34#issuecomment-228216443>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAq3YAIANVWHEa90Twg-wY3T1M87pmC_ks5qOxf5gaJpZM4IxVS3>
> .
>


-- 
Sent from Gmail Mobile

**Comment by philipcmonk** [comment]
I think we've got a quorum, with unanimous approval for merging this, so I'll go ahead and do that.

**Pull request merged**
