### PR TITLE
Fix architecture.md to allow site to build

### PR DESCRIPTION
**Pull request by ynx0**
Discussion from #1014 
cc @drbeefsupreme

### CODE REVIEW

**Comment by drbeefsupreme** [comment]
Thanks @ynx0 I think I actually made this mistake and didn't notice, then assumed it was your patch, I apologize! Thanks for fixing my mistake.

Now I am trying to merge your pull request again, but I think since the commits are already part of the tree, it says it will make no changes because of the reverts in the future... I am not quite sure what to do in this scenario. Perhaps if you create a new empty commit and then make the pull request, it will allow your changes to go through. But I am a git novice. @baudtack probably knows what to do

**Comment by ynx0** [comment]
@drbeefsupreme just looked up what to do in this exact scenario and someone on [stackoverflow](https://stackoverflow.com/a/28497372) suggests to revert the revert as a valid strategy :stuck_out_tongue:.

**Comment by ohAitch** [comment]
Yeah I suspect if you don't revert the revert and merge, the revert stands

**Comment by drbeefsupreme** [comment]
That was it. Thanks! Sorry for the mess :)

**Pull request merged**
