### PR TITLE
Hoon school - tapes use 24x the memory of cords

### PR DESCRIPTION
**Pull request by drbeefsupreme**
Just a one sentence edit based on a comment by @philipcmonk

----

#

### CODE REVIEW

**Comment by joemfb** [comment]
Yes, in u3. But the memory layout of a cell is unspecified, and other runtimes or memory models could cut that ratio substantially (ideally down to 1, but it might not be worth the trouble).

**Comment by syzygyzer** [comment]
Hmmm any suggestion then? Maybe I could just say "uses up to 24x the memory" instead of a precise figure?

**Comment by joemfb** [comment]
"In our runtime", "in, u3, our current runtime", ... Idk, we could honestly use some more precise vocabulary for such things.

But the underlying point is important, and shouldn't be waved away. A cell in arvo/hoon/nock is just the ordered association of two nouns, and a tape is just a cons-list of the bytes of a cord. How much memory a cell uses (6 32-bit words in u3) depends entirely on the memory model of the runtime -- it cannot be an intrinsic property within urbit.

**Comment by baudtack** [comment]
I feel like this is sending the wrong message. You should use tapes when you're planning to manipulate the data. The space constraints aren't something you're going to need to worry about for the most part. While it may be true, talking about this in the lists discussion is going to make people think they shouldn't ever use tapes because they are less memory efficient.

**Comment by syzygyzer** [comment]
> I feel like this is sending the wrong message. You should use tapes when you're planning to manipulate the data. The space constraints aren't something you're going to need to worry about for the most part. While it may be true, talking about this in the lists discussion is going to make people think they shouldn't ever use tapes because they are less memory efficient.

That's a really good point. I think from that context this discussion should possibly end up in the standard library docs instead, but if I were to do that I think it would be even more sensible to just have a discussion somewhere on how memory usage works in general (perhaps that already exists and I am forgetting).

I'll leave this open for now and think about it over the weekend.

**Comment by baudtack** [comment]
Anymore thoughts on this?

**Comment by drbeefsupreme** [comment]
I've come to the conclusion that including this wouldn't really contribute to understanding without a long diversion, probably a whole lesson, on how memory actually works, which doesn't exist. So I'm closing for now.

**Pull request closed without merging**
