### PR TITLE
Migrate urbit.org information architecture, language syntax markup

### PR DESCRIPTION
**Pull request by matildepark**
This PR simplifies the documentation directory structure according to the information architecture proposed and ratified across MarCom and Docs.

It also includes metadata for code blocks to render code blocks with syntax highlighting (Docs is currently marked up with C, Swift, Shell, and Hoon, among others). For future docs changes, it's as easy as writing the language after your first step of triple backticks. See the source for examples. 

nb. Syntax highlighting doesn't include Dojo-specific syntax.

Finally, all relative links are amended to reflect the directory changes. Installation and operations material is removed from documentation in favour of being hosted on their own directories on urbit.org. 

Links to that material might change, as I just need a final call on '/try' for installation materials. /develop will include the [development ship and community tutorials materials](https://boring-turing-42360d.netlify.com/develop/).

### CODE REVIEW

**Comment by rmariani** [comment]
Thanks Matilde! Forgive my ignorance, but what does ```hoon do?

**Comment by matildepark** [comment]
Yes, it tells what language the code's in so a Markdown renderer, if it knows how to render the syntax, can do so correctly. If it doesn't know, it just shows the code without highlighting as normal.

**Comment by rmariani** [comment]
Gotcha

**Comment by matildepark** [comment]
Cleared the merge conflict again.

**Comment by rmariani** [comment]
LGTM

**Pull request merged**
