### PR TITLE
split up clay.md

### PR DESCRIPTION
**Pull request by drbeefsupreme**
Split up the pages into more manageable sizes, on very minor changes to content to refer to new page structure.

### CODE REVIEW

**Review by jalehman — APPROVED** [review]
This looks good, although we might be able to do better than simply saying "parts of this document are out of date as of March 2021." What about, "Parts of this document are likely out of date as of March 2021, but we're actively working on updating them. If you'd like to help, please reach out to us at docs@tlon.io."

**Comment by matildepark** [comment]
Not that anyone asked my opinion, but it's actively hostile to the reader to not say which parts are outdated — it's literally toxic when gaining an understanding to provide wrong information. In general, we should make an effort to hide or delete old information, preferring to say nothing rather than the wrong thing when new developers seek context and gradual familiarity.

**Comment by drbeefsupreme** [comment]
I agree, and I've been actively working to figure out which information is out of date on this doc for a couple of months. It's just a lot of work going sentence by sentence and checking code to see whether or not its accurate. I previously just tried to wipe the whole thing #964 to avoid any wrong information, but that also got complaints. This isn't ideal, but its the best I can do given my limited time for now.

**Comment by matildepark** [comment]
Josh’s word comes first here! But I think Mark should know one bad apple spoils the bunch. Useful:inaccurate ratios are only useful for people like him.

— 
~haddef-sigwen
https://urbit.org

**Comment by drbeefsupreme** [comment]
@jalehman OK I updated it, but people outside Tlon cannot email docs@tlon.io so I suggested UC/docs or this repo.

**Pull request merged**
