### PR TITLE
Star ops

### PR DESCRIPTION
**Pull request by rmariani**
A high level explanation of the powers, responsibilities, and operations of stars.

### CODE REVIEW

**Comment by msutherl** [comment]
@rmariani made some changes. If you don't object, will merge.

**Comment by rmariani** [comment]
LGTM

**Comment by fche** [comment]
Would you consider explaining
- what "DNS routing" is
- what setting the the bare IP address (but not UDP port#!) enables
- and for bonus marks ... whether this is temporary, or whether a ship can learn its own external IP address(es) from upstream peers in the future

**Comment by ohAitch** [comment]
And in lieu of upstream peers, https://ifconfig.io or such!

**Comment by msutherl** [comment]
@fche created an issue for this here https://github.com/urbit/docs/issues/407

**Pull request merged**
