### PR TITLE
Mention the quiet flag in talk documentation.

### PR DESCRIPTION
**Pull request by Fang-**
What it says on the box. Quiet flag from urbit/arvo#300.

I'll update this to include the flag in urbit/arvo#308 if it gets accepted.

### CODE REVIEW

**Comment by galenwp** [comment]
Ha, works for me.

**Comment by ohAitch** [comment]
To me this is kind of starting to sound like we should
default-suppress presence notifications, and only use them to update
the web talk room occupancy display.

**Comment by galenwp** [comment]
That's fine with me

**Comment by cgyarvin** [comment]
100% agreed, let's try the patch

**Comment by galenwp** [comment]
By 'try the patch', you mean accept this?  Because muting them would require a separate patch...

**Comment by cgyarvin** [comment]
That's what I mean!  Sorry.

**Comment by Fang-** [comment]
If nobody's on this yet I'll probably pick this up in the coming days. Do we prefer `quiet` to be on by default, or do we want to replace it with a `loud` option?

**Comment by r0br0dz** [comment]
Quiet by default. Loud as an option similar to Verbose. Seems standard to
me and good. :)
Great project and vision btw

**Pull request merged**
