### PR TITLE
Change Urbytes comet name to more generic ~sampel_sipnem.

### PR DESCRIPTION
**Pull request by keatondunsford**
Try to make the comet name in the Urbytes more general ("sample ship name"). Gave me a
laugh too (thanks Raymond).

### CODE REVIEW

**Comment by cgyarvin** [comment]
I personally always hated this one, but others can weigh in...

**Comment by cgyarvin** [comment]
After a night's sleep, I continue to hate it.  Ship names that are puns
just seem tacky to me.

**Comment by galenwp** [comment]
I like to just use `~your-urbit` or `~your_urbit`.  Could also do `~your-planet` or `~your_comet`.

**Comment by cgyarvin** [comment]
I don't absolutely object to that style, but in my own docs I just prefer a
nice random name.

On Wed, Feb 8, 2017 at 10:41 AM, Galen Wolfe-Pauly <notifications@github.com

**Comment by galenwp** [comment]
I'm not particularly opinionated about this either, but we should be consistent.

**Comment by cgyarvin** [comment]
Fine, let's do it my way. :-)

On Wed, Feb 8, 2017 at 10:51 AM, Galen Wolfe-Pauly <notifications@github.com

**Comment by keatondunsford** [comment]
I'm going to add a comment in the Urbyte that upon booting, your comet should look something like `actual_@p_shipname`. But then after that use your-urbit. Consistency is important but yeah I agree with tackiness being a poor choice. Just wanted to clarify that format that it should look like, since `@p` will likely throw some newbies off compared to something like a Unix username.

**Comment by cgyarvin** [comment]
Sorry, I prefer an actual random shipname all the way through.  I feel
~your-urbit introduces a kind of inconsistency of feel that I don't like.

**Comment by keatondunsford** [comment]
I agree the consistency of `@p` format is important. @galenwp Approve? We could also just come up with a less cheesy consistent `@p` ship name. Basically, the planet/comet equivalent of ~zod.

`~dapnep-ronmyl` is the very first planet at ``@u`65.535`.

**Comment by galenwp** [comment]
Yeah, I don't mind using an actual ship name at all.  Consistency is paramount, and it'd be nice to explain in some introductory doc that 'we're going to use `~dapnep-ronmyl`, although yours will be something else'.

**Comment by cgyarvin** [comment]
Yes.

On Wed, Feb 8, 2017 at 11:27 AM, Galen Wolfe-Pauly <notifications@github.com

**Comment by keatondunsford** [comment]
I like ~doznec-dozzod better. I'll go through with it.

**Comment by cgyarvin** [comment]
Could we get a normal-sounding name, not an unusual-sounding one?

**Comment by galenwp** [comment]
Agreed.  I like `~dapnep-ronmyl` better.

**Comment by keatondunsford** [comment]
K.

On Wed, Feb 8, 2017 at 11:39 AM, Galen Wolfe-Pauly
<notifications@github.com> wrote:
> Agreed. I like ~dapnep-ronmyl better.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Keaton Dunsford
https://keybase.io/keat
https://tonret-sigsur.urbit.org

**Pull request closed without merging**
