### PR TITLE
Create contributing.md (& minor fixes)

### PR DESCRIPTION
**Pull request by asgardiator**
Part 1 of #21 
  * Create `contributing.md`
  * Link to twigs in `arvo/basic.md`
  * Hunt and eliminate stray comma

### CODE REVIEW

**Comment by galenwp** [comment]
Sorry, I missed this one the other day.  I think that your contributing doc should at least link to https://github.com/urbit/urbit/blob/master/CONTRIBUTING.md.  

Or perhaps that doc should be duplicated in the docs?  It's annoying to maintain then together, and a repo should have a `CONTRIBUTING.md`.  What do you think?

**Comment by asgardiator** [comment]
How's that?

**Comment by galenwp** [comment]
Looks good.  Did you try rendering the switch away from `<blockquote class='blockquote'>`?  I hated taht style, but it was a bootstrap thing.  I think I added the needed CSS to drop the class.  Is that right?

**Comment by asgardiator** [comment]
Yeah, you can see a rendered example already in
http://urbit.org/docs/arvo/basic/ so it seems to work just fine. Anyway,
<blockquote> seems to increase font size, which doesn't strike me as useful
or intended.

**Comment by galenwp** [comment]
Yep, I did update that CSS.  Merged!  Thanks!

**Pull request merged**
