### PR TITLE
adds 'decorum' section

### PR DESCRIPTION
**Pull request by rmariani**
Gently massaged from the google doc

### CODE REVIEW

**Comment by baudtack** [comment]
Maybe it's just me but maybe it would be worth making clear more than once that these are only rules that affect the tlon run parts of the network and that not only will tlon not police anything else, but we're literally incapable of doing so.

**Comment by ohAitch** [comment]
Decorum request: don't mix hard-wrapped and non-hard-wrapped lines in the
same document :)

**Comment by rmariani** [comment]
I'll make that clearer @baudtack

**Comment by ohAitch** [comment]
The "incapable of doing so" part?

**Comment by rmariani** [comment]
Yeah, upon re-reading it, I think that making it any clearer would be unnecessary and forced

**Comment by rmariani** [comment]
@ohAitch I fixed the wrapping :)

**Comment by rmariani** [comment]
Ok, I added something to drive the point home.

**Pull request merged**
