### PR TITLE
upgrade centar docs

### PR DESCRIPTION
**Pull request by belisarius222**
Add discussion and a couple more examples.

### CODE REVIEW

**Comment by cgyarvin** [comment]
This is the one rune I never use.

**Comment by ohAitch** [comment]
!,

**Comment by belisarius222** [comment]
It showed up [here in hoon.hoon](https://github.com/urbit/arvo/blob/maint-20170614/arvo/hoon.hoon#L9316), which is used by the ford rune `/:`, so I was trying to make sense of it.

**Comment by keatondunsford** [comment]
At first glance, usage of this rune looks really ugly compared to the standard centis irregular syntax for this simple example. But it's in the system and should be documented, plus there might be some special case I'm not thinking about where it'd be useful.

Thanks for the update!

**Comment by ohAitch** [comment]
An example with bunting a mold would be useful, yeah

**Comment by Fang-** [comment]
[For example.](https://github.com/Fang-/arvo/blob/talk-split/app/talk-agent.hoon#L415)

**Pull request merged**
