### PR TITLE
Update interface.md

### PR DESCRIPTION
**Pull request by rmariani**
Links were broken

### CODE REVIEW

**Comment by keatondunsford** [comment]
Can you change these to the relative path (like the current link), so that these can still be viewed on localhost? E.g. if I'm viewing a copy of the docs on my local ship, they should point to my local Clay file, rather than redirect me to urbit.org. The current relative link system used here and throughout the docs works, if you set them up that way.

**Comment by rmariani** [comment]
Sure, I just thought that the issue might have been the relative paths

**Comment by keatondunsford** [comment]
Try `[new gall](new-gall))` and `#[Hall's architecture](architecture)`.

**Comment by keatondunsford** [comment]
Cool. Can you also rebase the changes on your branch against origin/master to squash this into a single commit? It's an easy thing that you can Google how to do. Something like:

```
git rebase -i origin/master
```

Then change the left letters to 'f' to squash them and throw away their commit/message history, to boil these down into the first commit to be made to current origin/master.

Let me know if that doesn't make sense.

**Comment by keatondunsford** [comment]
Closed in favor of #254 (helped Rob with this).

**Pull request closed without merging**
