### PR TITLE
Straighten out the Accepts and Produces sections of docs/hoon/library…

### PR DESCRIPTION
**Pull request by jfranklin9000**
…/4m.md.

All of the Accepts sections were empty and the Produces sections had what should have been in Accepts so I moved them there and filled out the Produces sections.

I'm not sure about `++slav`, `++slaw`, `++slay` and `++stab`.

### CODE REVIEW

**Comment by joemfb** [comment]
`++slay` parses `txt` (a cord) for any atom, producing `(unit coin)`.

`++slaw` parses `txt` (a cord) for an atom with an aura of `mod`, producing `(unit @)`. (it only works with `++dime`, not any `++coin`)

`++slav` is `(cork slaw need)`; it produces the atom from `++slaw`, crashing if null.

`++stab` parses a cord for a path, producing a path or crashing if it can't.

BTW, this doc consistently says "parse span" where it should say "parse a cord".

**Comment by jfranklin9000** [comment]
I'll incorporate these changes and resubmit.  But "parse span" should be changed to "parse a knot" (except for `++stab` which does indeed parse a `++cord`).

However, since a `++knot` (`@ta`) is a `++cord` (`@t`) should I change them to "cord"?

**Comment by cgyarvin** [comment]
Might as well stick with "cord" for all of them.  But it doesn't matter
that much!

**Comment by ohAitch** [comment]
I mean, they do parse a knot, like if you give them a non-knot cord they'll
error cleanly but anything that's a valid slay/slaw/slav atom-as-text
format is valid @ta

**Comment by jfranklin9000** [comment]
I've incorporated ~master-morzod's input to the PR (except the `++dime` info; didn't know how to express that).  I used `cord` instead of `knot`.

**Pull request merged**
