### PR TITLE
tutorial: Deploy a ship to Azure Container Instances

### PR DESCRIPTION
**Pull request by eamsden**
I have put this tutorial through a start-to-finish test-run, deploying a comet to Azure Container Instances and accessing its Landscape by putting its FQDN in my browser.

@jalehman

### CODE REVIEW

**Comment by baudtack** [comment]
@vvisigoth do we have an azure account somewhere i can use to verify these instructions?

**Comment by eamsden** [comment]
@baudtack if you create one with a fresh email you get $200 in AWS credits (I don't recall needing any payment information).

**Review by baudtack — APPROVED** [review]

**Comment by jalehman** [comment]
@baudtack This should certainly be on the docs, but not here any more. This is usage-oriented content that should be on urbit.org under `/using`, ideally nested within `/using/running` somewhere.

**Comment by drbeefsupreme** [comment]
@eamsden This ended up in the wrong spot because of the reorg. Can you open another PR on the urbit.org repo and throw it into the `using/running` folder? Also make sure to add it to `using/running/_index.md`. Thanks!

**Pull request merged**
