### PR TITLE
Clarify React in Landscape and fix a couple of minor typos.

### PR DESCRIPTION
**Pull request by davis68**

### CODE REVIEW

**Comment by rmariani** [comment]
Thanks for this improvement

**Comment by jfranklin9000** [comment]
"In your pier, replace the code in `urbit/app/testing.hoon` with the Hoon code below."

That path isn't in your pier.  Change to:

"Replace the code in `urbit/app/testing.hoon` with the Hoon code below."

---

IIUC, for iteration you edit `tile/tile.js` and/or `urbit/app/testing.hoon`, then run `npm run build` (assume `npm run serve` hasn't been run).

This will update `urbit/app/testing/js/tile.js` (from `tile/tile.js`)  and then copy:

`urbit/app/testing.hoon` to `~your-pier/home/app/testing.hoon`
`urbit/app/testing/js/tile.js` to `~your-pier/home/app/testing/js/tile.js`

(`~your-pier/home` is what you entered when you ran `npm install`)

Then run `|commit %home` from the dojo.

Is this correct?

**Comment by davis68** [comment]
- Replacing "pier" with "project".

That process looks correct.  I'll add it as an explanatory note.

(I'm the JS/React noob here, trying to clarify what didn't make sense when I first started this module.)

**Comment by davis68** [comment]
#709 responds to this.

**Pull request merged**
