### PR TITLE
Change to meson

### PR DESCRIPTION
**Pull request by eglaysher**
This is a first draft of changes to the install documentation for meson. It works for brew based systems, but macports and all the other package managers still need to be updated.

### CODE REVIEW

**Comment by eglaysher** [comment]
The [Filesystem Hierarchy Standard](https://wiki.debian.org/FilesystemHierarchyStandard) says that locally compiled binaries go in `/usr/local/bin`. Or: yes, people are using /usr/local for urbit.

**Comment by mikolajpp** [comment]
Well, actually (;-), this is about preventing clashes between in-house software and distro supplied. Since we urbit is actually the only bundle we provide, it could safely go into /usr. /usr/local is for these cases where there could be clashes between distro provided software and locally installed one. I for one install my urbit into /usr.

Regardless of the fact where we put the fact, one thing is missing:
the libraries against which urbit is compiled should also be installed: after all we did provide all the fallback libraries. 

So the proper installation is to actually configure the install path and install using `ninja` install command.

**Comment by joemfb** [comment]
BTW, I just confirmed that you don't have to explicitly `git submodule init` and update, meson will handle that for you.

**Comment by keatondunsford** [comment]
@joemfb That's cool. Probably doesn't hurt to just keep it in the script though, unless you want to take it out.

**Comment by mikolajpp** [comment]
@joemfb you may want to see my PR to your branch.

`~palfun-foslup` needed compiling h2o, so I added meson.build as well as subprojects basing off your branch.

**Comment by mikolajpp** [comment]
Also, for some reason @joemfb your branch has missing flags (funsigned-char) which caused that recent bug.

**Comment by joemfb** [comment]
I was hoping we could just remove the bootstrap script, but I tested on Ubuntu Xenial, and legacy meson does not handle submodules automatically.

**Comment by keatondunsford** [comment]
I updated the Install page, and I was able to boot a fake ~zod with the Meson-PR branch. If we hit any issues, we can deal with them -- but, this all looks good to me. Merging!

**Comment by keatondunsford** [comment]
Wait, don't we want to install Meson through `pip` to get the latest version?

**Pull request merged**
