### PR TITLE
Concatenates child rune-pages into parent pages

### PR DESCRIPTION
**Pull request by rmariani**
The navbar only goes four levels deep, and individual rune-pages are five deep.

This also updates the fakezod instructions in `getting-started.udon`. 

Also addresses https://github.com/urbit/docs/issues/332

### CODE REVIEW

**Comment by msutherl** [comment]
@rmariani will merge when we have the new build process set up

**Comment by ohAitch** [comment]
Would this be a good test case for using ford runes to pull in dependencies?

**Comment by msutherl** [comment]
@ohAitch perhaps eventually

**Comment by rmariani** [comment]
Pushing more concatenations soon, so closing this for now. I will re-open when those changes are pushed.

**Comment by rmariani** [comment]
Ok. Every file is now level four at the deepest. I also added a table of contents on a few pages to make them more manageable.

**Comment by vvisigoth** [comment]
@rmariani can you fix merge conflict on getting-started.udon, plz.?

**Comment by rmariani** [comment]
on it

**Comment by rmariani** [comment]
Done

**Comment by ohAitch** [comment]
https://localhost:80 feels fishy

**Pull request merged**
