### PR TITLE
Small Tweaks to Docs

### PR DESCRIPTION
**Pull request by cxk280**
I made a few small typographical fixes to the Arvo tutorial. I also added an extra hint to the **Basic Hoon** page that I thought should have been there when first working through the tutorial myself.

### CODE REVIEW

**Comment by Fang-** [comment]
One tiny thing you missed is extra spaces in front of the `:-(a b)` so that it gets rendered as a code block again. Other than that, looks good, thank you!

**Comment by galenwp** [comment]
@cxk280 if you can make that change I'd be glad to merge this.  Thanks!

**Comment by cxk280** [comment]
I have reformatted the relevant characters as code. Additionally, since it is very short, I made it inline instead of a separate block.

**Comment by Fang-** [comment]
Looks good. Much appreciated!

**Pull request merged**
