### PR TITLE
changed basic operation to administration

### PR DESCRIPTION
**Pull request by heow**
When I first clicked on "basic operation" I was surprised to find Unixy admin stuff.  Broke it up into administration: everything "outside" of Urbit and operation: everything "inside" Urbit.  

At least it makes sense to me, I won't feel bad this gets kicked back.

### CODE REVIEW

**Comment by galenwp** [comment]
This seems reasonable.  Give me a bit to think it over, and to try it out in a browser to see how it feels.

**Comment by heow** [comment]
Title of "Basic Administration and Operation" is too long for the navigation, going to play with it a bit.

**Comment by galenwp** [comment]
What about 'administration and operation'?  I agree that administration sounds like something you do from Unix.

**Comment by heow** [comment]
"Administration and Operation" work well, it's not too wide on the docs/ screen but just a hair too wide inside admin/.  (see screenshots)

**Comment by heow** [comment]
screen1
screen2

**Comment by heow** [comment]
"subject oriented programming" has the same too-wide issue, both are readable

**Comment by galenwp** [comment]
Doesn't look *too* terrible.  We could add some kind of fade on the side of the nav.  (It should expand when you mouse over it, by the way).

What browser is that?  The underlines seem to be rendering at the bottom of the line height.  Firefox?

**Comment by heow** [comment]
Yes it's Firefox where it looks like a separator, Chrome renders as a proper underline.

**Comment by galenwp** [comment]
Okay, I think the display bug is fixed.  Want to push a fix for that title change?

**Comment by galenwp** [comment]
Thanks!

**Pull request merged**
