### PR TITLE
Create test directory and files in sandbox instead of home since we'r…

### PR DESCRIPTION
**Pull request by jfranklin9000**
…e serving sandbox.

Please double-check.

### CODE REVIEW

**Comment by joemfb** [comment]
FWIW, I kind of favor the opposite. It's worth documenting that you *can* switch the desk you're serving, but I don't think this should recommend that everyone do so. My $0.02 ...

**Comment by jfranklin9000** [comment]
The previous page `http://urbit.org/~~/docs/using/filesystem/` Quickstart section creates a `%sandbox` desk and mounts it, then the Quickstart section of this page `http://urbit.org/~~/docs/using/web/` serves `%sandbox` but creates files in `home`.  It's inconsistent and confusing.  It needs clarification one way or another.

**Comment by joemfb** [comment]
I absolutely agree with that. And I forgot the filesystem doc already has you creating and mounting `%sandbox`, so your changes seem like the right approach.

**Comment by galenwp** [comment]
The idea was to avoid possibilities of creating merge conflicts. That's why we use %sandbox.

**Comment by galenwp** [comment]
Anyway, thanks for catching this.  Looks correct to me.

**Pull request merged**
