### PR TITLE
Galaxy docs for comment

### PR DESCRIPTION
**Pull request by zaphar**
Probably don't want to merge this as right now. But now would be a good time to comment on the structure of the document as proposed and perhaps we can do some discussion here about what the missing content of each section should be.

I'm certainly not the expert on Galaxy administration and Ops/OpSec but this should be a decent starting point.

When we feel somewhat confident about the content I can squash and it can be merged in.

### CODE REVIEW

**Comment by rmariani** [comment]
Thanks for writing this, Jeremy. I am going to close this for now, but know that this is on our radar. There's a greater project to document star and galaxy ops, and this will be absorbed into it. Feel free to keep working on this!

**Comment by rmariani** [comment]
I am actually going to keep this open for a bit, in case anyone else cares to give suggestions.

**Comment by zaphar** [comment]
I am more than happy to let someone more qualified than me to take this over :-D so it's good to know that you guys are working on it.

Feel free to close it if you no one else comments on it.

**Comment by rmariani** [comment]
We like outside perspectives :)

**Pull request closed without merging**
