### PR TITLE
Azimuth typos + removing "Aegean" mention

### PR DESCRIPTION
**Pull request by matildepark**
Was reading the Azimuth article, saw some stuff to amend -- like linking to the Node repos (and changing the name of the second one), changing "Aegean" to "Landscape" (there's no other mentions of Aegean in the docs and Landscape best fits what it describes), and so I am putting in a PR here.

### CODE REVIEW

**Comment by rmariani** [comment]
Aegean is a different concept from Landscape AFAIK: https://urbit.org/primer/#what-urbit-is-for

We never really talk about Aegean, so it's probably worth cutting the reference.

**Comment by matildepark** [comment]
Oh, interesting. I see, I see. Isn't "the pattern for **creating software experiences** for individual Urbit communities" Landscape, then, and Aegean the pattern of societies themselves?

Dunno. I can just remove Landscape from this.

**Comment by matildepark** [comment]
Ok, I just rephrased it so if/when Aegean comes up we can add it in seamlessly later. Leaving Aegean in with no other references to it in the Docs is less preferable and Landscape is less exact.

**Comment by rmariani** [comment]
Landscape is one software experience, one that we made.

But looks good, thanks

**Pull request merged**
