### PR TITLE
Arvo

### PR DESCRIPTION
**Pull request by mattlevan**
I've spent some quality time going through the docs and doing my best to sync them with @keatondunsford's work on the examples repo, which is fantastic. The hoon has been copied over faithfully and I've worked with friendly folks in urbit-meta to update and clarify explanations as well. 

Of these, I think the most controversial section will be the removal of the "layer" analogy when describing ducts, at the end of the network doc. 

Hope this helps! Please let me know of any changes I can make to improve this, and I will do my best to accomodate them. This has been a great learning experience for me, so I'm happy to continue with the rest of the arvo docs as well.

### CODE REVIEW

**Comment by ngzax** [comment]
@mattlevan : Looks like your changes and mine and mostly completely overlapping. great minds think alike. 😄 . I will defer and just wait for this to be merged. Looks like you will need to merge the most recent docs/master and push a new commit to resolve the conflicts first, though.

**Comment by mattlevan** [comment]
Thanks @ngzax I'll be on later this afternoon to fix that.

**Comment by keatondunsford** [comment]
@mattlevan This is super helpful. Thanks so much man. Going to merge this now!

**Comment by mattlevan** [comment]
Thanks @keatondunsford, will be finishing the rest of the arvo .md files soon!

**Comment by mattlevan** [comment]
Awesome, will do. Thanks for noticing that. I was using `/app/echo/hoon` (as an example) but I will replace that convention with the full clay path, which is `/=examples=/app/echo/hoon`.

Added as issue [#3](https://github.com/mattlevan/docs/issues/3) in [my fork](https://github.com/mattlevan/docs).

**Pull request merged**
