### PR TITLE
tutorial: deploy a ship to AWS Elastic Container Service

### PR DESCRIPTION
**Pull request by eamsden**
***DRAFT***
This PR is part of https://grants.urbit.org/proposals/626138244-docker-image-for-cloud-container-orchestration

@baudtack I would like guidance on:

- [ ] Where is the appropriate place to put screenshots, and how to reference them from the markdown source in their proper location.
- [ ] How to style inline screenshots so that they are properly scaled, and so that instructional text does not get lost among them.

### CODE REVIEW

**Comment by baudtack** [comment]
I actually don't really know. @matildepark ?

**Comment by matildepark** [comment]
We use GCP and media.urbit.org.

- @baudtack can upload these images to media.urbit.org (I'll DM him the bucket) and list the URLs here
- @eamsden can change the URLs in his commit.

**Comment by eamsden** [comment]
@matildepark @baudtack thanks!

**Comment by matildepark** [comment]
Much apologies — you'll have to retarget this against https://github.com/urbit/urbit.org/tree/master/content/docs.

**Pull request closed without merging**
